<a href="https://colab.research.google.com/github/Anikeje2/Data-Science-Journey/blob/main/Customer_Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer  #importing libraries
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/SCA class/customer_data.csv') # loading dataset

In [ ]:
df.info()
print('------------')
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CustomerID          100 non-null    int64
 1   Age                 86 non-null     float64
 2   Income              87 non-null     float64
 3   Gender              98 non-null     object
 4   City                100 non-null    object
 5   Education           100 non-null    object
 6   Years_as_Customer   100 non-null    int64
 7   Num_Products        100 non-null    int64
 8   Last_Purchase_Days  100 non-null    int64
 9   Purchased           100 non-null    object
dtypes: float64(2), int64(4), object(4)
memory usage: 7.9+ KB
------------

,CustomerID,Age,Income,Years_as_Customer,Num_Products,Last_Purchase_Days
count,100.000000,86.000000,87.000000,100.000000,100.000000,100.000000
mean,50.500000,38.639535,59333.333333,5.690000,3.210000,28.560000
std,29.011492,10.254311,29523.410761,3.628437,1.805127,29.806555
min,1.000000,22.000000,15000.000000,1.000000,1.000000,1.000000
25%,25.750000,29.250000,31500.000000,2.000000,2.000000,6.000000
50%,50.500000,38.000000,61000.000000,5.000000,3.000000,15.000000
75%,75.250000,46.000000,82500.000000,8.000000,5.000000,44.250000
max,100.000000,61.000000,120000.000000,15.000000,7.000000,100.000000

In [ ]:
df.isnull().sum() #checking missing data

CustomerID             0
Age                   14
Income                13
Gender                 2
City                   0
Education              0
Years_as_Customer      0
Num_Products           0
Last_Purchase_Days     0
Purchased              0
dtype: int64

In [ ]:
#using simple imputer to fill all missing age with the median age
imputer = SimpleImputer(strategy = 'median')
df['Age']= imputer.fit_transform(df[['Age']])


#using simple imputer to fill all missing gender with the mode,the most frequent gender
impute =SimpleImputer(strategy='most_frequent')
df['Gender']= impute.fit_transform(df[['Gender']])[:, 0]

Median was used for Age to reduce the effect of outliers. Mode was used for Gender because it is a categorical data.

In [ ]:
df = df.dropna(subset=['Income']) #dropping missing income

In [ ]:
df.isnull().sum() #rechecking missing data

CustomerID            0
Age                   0
Income                0
Gender                0
City                  0
Education             0
Years_as_Customer     0
Num_Products          0
Last_Purchase_Days    0
Purchased             0
dtype: int64

In [ ]:
#converting gender to binary by label encoding
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])

Gender was label encoded to convert it into numerical form because it is a ordered data. So it is binary now

In [ ]:
df = pd.get_dummies(df, columns=['City'])

In [ ]:
df['Purchased'] = le.fit_transform(df['Purchased']) #converting purchase to binary by label encoding

In [ ]:


age = df[['Age']]   #using standard scale on age
scaler = StandardScaler()
age_scaled = scaler.fit_transform(age)

In [ ]:
df['Age_scaled'] = age_scaled  #comparing original age and scaled age
df[['Age', 'Age_scaled']].head()

    Age  Age_scaled
0  34.0   -0.494719
1  38.0   -0.084809
2  28.0   -1.109585
4  52.0    1.349877
5  23.0   -1.621972

In [ ]:
income =df[['Income']]
scaler = MinMaxScaler()
income_scaled = scaler.fit_transform(income)

In [ ]:
df['Income_scaled'] = income_scaled #comparing original income and scaled income
df[['Income', 'Income_scaled']].head()

    Income  Income_scaled
0  45000.0       0.285714
1  72000.0       0.542857
2  31000.0       0.152381
4  98000.0       0.790476
5  18000.0       0.028571

The City variable was one-hot encoded to prevent false relationships between categories. Gender and Purchased were label encoded to convert them into numerical form suitable for modeling. Age and Income were scaled using StandardScaler and MinMaxScaler to ensure consistent feature ranges and improve model performance.